[package]
name = "waldo"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = "0.2"
flume = "0.11"
memmap2 = "0.9"
io-uring = "0.7"
thiserror = "2.0"
core_affinity = "0.8"
xxhash-rust = {version = "0.8", features = ["xxh3", "const_xxh3"]}

[profile.release]
debug = true